import re
import time
from typing import Dict, List, Any, Tuple
import subprocess
import tempfile
import os

# Import MeTTa interpreter (same as working MeTTa Rule Builder)
try:
    # Optional Hyperon MeTTa runtime (support both package names)
    try:
        from hyperonpy import MeTTa  # type: ignore
        HYPERON_AVAILABLE = True
        HYPERON_BACKEND = 'hyperonpy'
    except Exception:
        from hyperon import MeTTa  # type: ignore
        HYPERON_AVAILABLE = True
        HYPERON_BACKEND = 'hyperon'
except Exception:
    MeTTa = None  # type: ignore
    HYPERON_AVAILABLE = False
    HYPERON_BACKEND = None

class MeTTaService:
    """Service for MeTTa file generation and query execution."""
    
    def __init__(self):
        self.supported_operators = ['==', '!=', '>', '<', '>=', '<=']
    
    def generate_metta_file(self, session_id: str, session_manager, rule_service) -> Dict[str, Any]:
        """Generate MeTTa file from session data."""
        try:
            # Get session data
            session_data = session_manager.get_session(session_id)
            if not session_data:
                return {
                    'success': False,
                    'error': {
                        'code': 'SESSION_NOT_FOUND',
                        'message': 'Session not found'
                    }
                }
            
            # Get CSV data
            csv_data = session_data.get('csv_data')
            if not csv_data:
                return {
                    'success': False,
                    'error': {
                        'code': 'NO_CSV_DATA',
                        'message': 'No CSV data found in session'
                    }
                }
            
            # Get rules
            rules = rule_service.get_rules(session_id)
            
            # Generate MeTTa content
            metta_content = self._build_metta_content(csv_data, rules)
            
            # Calculate stats
            lines = metta_content.split('\n')
            facts_count = len([line for line in lines if line.strip() and not line.startswith(';') and not line.startswith('=') and not line.startswith('!')])
            rules_count = len([line for line in lines if line.strip().startswith('=')])
            
            return {
                'success': True,
                'metta_content': metta_content,
                'file_size': len(metta_content.encode('utf-8')),
                'lines_count': len(lines),
                'facts_count': facts_count,
                'rules_count': rules_count
            }
            
        except Exception as e:
            return {
                'success': False,
                'error': {
                    'code': 'GENERATION_ERROR',
                    'message': f'Failed to generate MeTTa file: {str(e)}'
                }
            }
    
    def _build_metta_content(self, csv_data: Dict[str, Any], rules: List[Dict[str, Any]]) -> str:
        """Build MeTTa file content."""
        content_lines = [
            ";; File: knowledge_base.metta",
            ";; Generated by MeTTa Rule Builder",
            "",
            ";; --- DATA FROM CSV ---"
        ]
        
        # Add CSV facts
        if csv_data.get('success') and csv_data.get('facts'):
            for fact in csv_data['facts']:
                content_lines.append(fact)
        
        content_lines.extend(["", ";; --- RULES FROM UI ---"])
        
        # Add rules
        for rule in rules:
            rule_content = self._generate_rule_content(rule)
            if rule_content:
                content_lines.append(rule_content)
        
        # Add example queries
        content_lines.extend([
            "",
            ";; --- EXAMPLE QUERIES ---",
            ";; Uncomment and modify these queries to test your knowledge base:",
            ";; !(match &self (Name $x $y) ($x $y))",
            ";; !(match &self (Age $x $age) (if (> $age 25) $x ()))"
        ])
        
        return '\n'.join(content_lines)
    
    def _generate_rule_content(self, rule: Dict[str, Any]) -> str:
        """Generate MeTTa rule content from rule data."""
        try:
            rule_type = rule.get('rule_type', 'flexible')
            
            if rule_type == 'match':
                return self._generate_match_rule(rule)
            elif rule_type in ['findDetail', 'findByCondition', 'findByConditionFull']:
                return self._generate_advanced_rule(rule)
            else:
                return self._generate_flexible_rule(rule)
                
        except Exception as e:
            return f";; Error generating rule: {str(e)}"
    
    def _generate_match_rule(self, rule: Dict[str, Any]) -> str:
        """Generate match-based rule."""
        function_name = self._sanitize_function_name(rule.get('function_name', 'action'))
        variable_name = rule.get('variable_name', '$x')
        condition = rule.get('condition', {})
        true_action = rule.get('true_action', '$x')
        false_action = rule.get('false_action', '()')
        
        column = condition.get('column', 'Field')
        operator = condition.get('operator', '==')
        value = condition.get('value', '')
        
        # Sanitize column name
        col_name = self._sanitize_column_name(column)
        
        # Format value
        value_atom = self._format_value(value)
        
        # Build condition
        if operator == '==':
            condition_expr = f"(if (== $value {value_atom}) {true_action} {false_action})"
        elif operator == '!=':
            condition_expr = f"(if (== $value {value_atom}) {false_action} {true_action})"
        else:
            condition_expr = f"(if ({operator} $value {value_atom}) {true_action} {false_action})"
        
        # Build match pattern
        match_pattern = f"({col_name} {variable_name} $value)"
        
        return f"(= ({function_name} {variable_name})\n     (match &self {match_pattern} {condition_expr}))"
    
    def _generate_flexible_rule(self, rule: Dict[str, Any]) -> str:
        """Generate flexible rule."""
        function_name = self._sanitize_function_name(rule.get('function_name', 'action'))
        parameter = rule.get('parameter', '$person')
        condition = rule.get('condition', {})
        true_action = rule.get('true_action', 'True')
        false_action = rule.get('false_action', 'False')
        
        column = condition.get('column', 'Field')
        operator = condition.get('operator', '==')
        value = condition.get('value', '')
        
        # Sanitize column name
        col_name = self._sanitize_column_name(column)
        
        # Format value
        value_atom = self._format_value(value)
        
        # Build condition
        if operator == '==':
            condition_expr = f"(if (== ({col_name} {parameter}) {value_atom}) {true_action} {false_action})"
        elif operator == '!=':
            condition_expr = f"(if (== ({col_name} {parameter}) {value_atom}) {false_action} {true_action})"
        else:
            condition_expr = f"(if ({operator} ({col_name} {parameter}) {value_atom}) {true_action} {false_action})"
        
        return f"(= ({function_name} {parameter})\n     {condition_expr})"
    
    def _generate_advanced_rule(self, rule: Dict[str, Any]) -> str:
        """Generate advanced MeTTa rule (findDetail, findByCondition, findByConditionFull)."""
        rule_type = rule.get('rule_type', 'findDetail')
        function_name = self._sanitize_function_name(rule.get('function_name', 'findDetail'))
        
        if rule_type == 'findDetail':
            return self._generate_find_detail_rule(rule)
        elif rule_type == 'findByCondition':
            return self._generate_find_by_condition_rule(rule)
        elif rule_type == 'findByConditionFull':
            return self._generate_find_by_condition_full_rule(rule)
        else:
            return f";; Unknown advanced rule type: {rule_type}"
    
    def _generate_find_detail_rule(self, rule: Dict[str, Any]) -> str:
        """Generate findDetail rule."""
        function_name = self._sanitize_function_name(rule.get('function_name', 'findDetail'))
        output_format = rule.get('output_format', '($c $x)')
        
        return f"""(= ({function_name} $id)
     (match &self ($c $id $x)  {output_format})
)"""
    
    def _generate_find_by_condition_rule(self, rule: Dict[str, Any]) -> str:
        """Generate findByCondition rule."""
        function_name = self._sanitize_function_name(rule.get('function_name', 'findByCondition'))
        column = self._sanitize_column_name(rule.get('column', 'Field'))
        operator = rule.get('operator', '>')
        value = self._format_value(rule.get('value', '0'))
        
        return f"""(= ({function_name} $x)
     (match &self ($x $y $z) (if ({operator} $y  {value}) $y  ()))
)"""
    
    def _generate_find_by_condition_full_rule(self, rule: Dict[str, Any]) -> str:
        """Generate findByConditionFull rule."""
        function_name = self._sanitize_function_name(rule.get('function_name', 'findByConditionFull'))
        column = self._sanitize_column_name(rule.get('column', 'Field'))
        operator = rule.get('operator', '>')
        value = self._format_value(rule.get('value', '0'))
        output_format = rule.get('output_format', '("user" $c "is" , $value)')
        
        return f"""(= ({function_name} $x)
     (match &self ($x $y $z) (if ({operator} $y  {value}) (match &self ($c $y $value)  {output_format}  )  ()))
)"""
    
    def generate_rule_preview(self, rule: Dict[str, Any]) -> str:
        """Generate preview of a single rule."""
        return self._generate_rule_content(rule)
    
    def execute_query(self, session_id: str, query: str, session_manager, rule_service) -> Dict[str, Any]:
        """Execute MeTTa query on generated knowledge base."""
        try:
            # Check if MeTTa interpreter is available
            if not HYPERON_AVAILABLE:
                return {
                    'success': False,
                    'error': {
                        'code': 'METTA_NOT_AVAILABLE',
                        'message': f'MeTTa interpreter not available. Backend: {HYPERON_BACKEND}'
                    }
                }
            
            # Get generated MeTTa content
            metta_content = session_manager.get_generated_metta(session_id)
            if not metta_content:
                return {
                    'success': False,
                    'error': {
                        'code': 'NO_CONTENT',
                        'message': 'No MeTTa content generated yet'
                    }
                }
            
            # Execute real MeTTa query
            start_time = time.time()
            
            try:
                # Create MeTTa instance
                metta = MeTTa()
                print( "metta_content", metta_content)
                # Load knowledge base (facts + rules)
                metta.run(metta_content)
                
                # Execute the query
                result = metta.run(query)
                print( "result", result)
                
                # Convert result to strings for JSON friendliness
                # result may be a list of expressions; convert via str()
                if isinstance(result, (list, tuple)):
                    rendered = [str(r) for r in result]
                else:
                    rendered = [str(result)]
                
                execution_time = f"{time.time() - start_time:.3f}s"
                
                return {
                    'success': True,
                    'results': rendered,
                    'execution_time': execution_time
                }
                
            except Exception as metta_error:
                return {
                    'success': False,
                    'error': {
                        'code': 'METTA_EXECUTION_ERROR',
                        'message': f'MeTTa execution failed: {str(metta_error)}'
                    }
                }
            
        except Exception as e:
            return {
                'success': False,
                'error': {
                    'code': 'QUERY_EXECUTION_ERROR',
                    'message': f'Failed to execute query: {str(e)}'
                }
            }
    
    def get_metta_status(self) -> Dict[str, Any]:
        """Get MeTTa interpreter status."""
        return {
            'available': HYPERON_AVAILABLE,
            'backend': HYPERON_BACKEND,
            'message': 'MeTTa interpreter ready' if HYPERON_AVAILABLE else 'MeTTa interpreter not available'
        }
    
    def _sanitize_function_name(self, name: str) -> str:
        """Sanitize function name for MeTTa."""
        if not name:
            return "action"
        
        # Convert to camelCase
        return name[0].lower() + name[1:] if len(name) > 1 else name.lower()
    
    def _sanitize_column_name(self, name: str) -> str:
        """Sanitize column name for MeTTa."""
        parts = re.findall(r"[A-Za-z0-9]+", str(name))
        if not parts:
            return "Field"
        return "".join(p[0].upper() + p[1:] for p in parts)
    
    def _format_value(self, value) -> str:
        """Format value for MeTTa."""
        # Convert to string first
        str_value = str(value).strip()
        
        # Try to parse as number
        try:
            # Try int first
            int_val = int(str_value)
            return str(int_val)
        except ValueError:
            try:
                # Try float
                float_val = float(str_value)
                return str(float_val)
            except ValueError:
                # It's a string, but don't add extra quotes if it's already quoted
                if str_value.startswith('"') and str_value.endswith('"'):
                    # Already quoted, just return as is
                    return str_value
                else:
                    # Not quoted, add quotes
                    escaped = str_value.replace('"', '\\"')
                    return f'"{escaped}"'
