!(bind! &users (new-space))

; Example user data format (this will be populated automatically when users are created)
; User: bob - Added on 2024-01-01 12:00:00
; !(add-atom &users (user bob))
; !(add-atom &users (country bob "United States"))
; !(add-atom &users (language bob "English"))
; !(add-atom &users (language bob "Japanese"))
; !(add-atom &users (watched bob m_tt1198153))
; !(add-atom &users (watched bob m_tt0081506))
; !(add-atom &users (liked bob m_tt0162866))
; !(add-atom &users (liked bob m_tt0081506))
; !(add-atom &users (fav-genre bob "Drama"))
; !(add-atom &users (fav-genre bob "Action"))
; !(add-atom &users (fav-genre bob "History"))
; !(add-atom &users (fav-actor bob "Matthew McConaughey"))
; !(add-atom &users (fav-actor bob "Tomisaburô Wakayama"))
; !(add-atom &users (fav-actor bob "Minoru Ôki"))
; !(add-atom &users (fav-director bob "Alfonso Cuarón"))
; !(add-atom &users (fav-director bob "Robert Houston"))
; !(add-atom &users (fav-director bob "Christopher Nolan"))
; !(add-atom &users (writer bob "Kazuo Koike"))
; !(add-atom &users (dislike bob m_tt0162862))
; User: pinky - Added on 2025-09-22 15:48:42.330225
!(add-atom &users (user pinky))
!(add-atom &users (fav-genre pinky "Drama"))
!(add-atom &users (fav-genre pinky "Action"))
!(add-atom &users (fav-genre pinky "History"))
!(add-atom &users (fav-actor pinky "Matthew McConaughey"))
!(add-atom &users (fav-actor pinky "Tomisaburô Wakayama"))
!(add-atom &users (fav-actor pinky "Minoru Ôki"))
!(add-atom &users (fav-director pinky "Alfonso Cuarón"))
!(add-atom &users (fav-director pinky "Robert Houston"))
!(add-atom &users (fav-director pinky "Christopher Nolan"))
!(add-atom &users (language pinky "English"))
!(add-atom &users (language pinky "Japanese"))
!(add-atom &users (country pinky "United States"))
!(add-atom &users (writer pinky "Kazuo Koike"))
!(add-atom &users (watched pinky m_tt1198153))
!(add-atom &users (watched pinky m_tt0081506))
!(add-atom &users (liked pinky m_tt0162866))
!(add-atom &users (liked pinky m_tt0081506))


; User: bob - Added on 2025-09-22 19:16:48.809042
!(add-atom &users (user bob))
!(add-atom &users (fav-genre bob "Drama"))
!(add-atom &users (fav-genre bob "Comedy"))
!(add-atom &users (fav-genre bob "Sci-Fi"))
!(add-atom &users (language bob "English"))
!(add-atom &users (language bob "Hindi"))
!(add-atom &users (country bob "United States"))
!(add-atom &users (country bob "India"))
!(add-atom &users (liked bob m_tt0060009))
!(add-atom &users (liked bob m_tt0222850))
!(add-atom &users (liked bob m_tt1885032))


; User: bob - Added on 2025-09-23 01:27:04.168116
!(add-atom &users (user bob))
!(add-atom &users (watched bob m_tt0032138))


; User: bob - Added on 2025-09-23 01:27:06.765881
!(add-atom &users (user bob))
!(add-atom &users (watched bob m_tt1465522))


; User: bob - Added on 2025-09-23 01:27:08.095812
!(add-atom &users (user bob))
!(add-atom &users (watched bob m_tt0795176))


; User: bob - Added on 2025-09-23 01:27:09.382859
!(add-atom &users (user bob))
!(add-atom &users (watched bob m_tt5491994))


; User: bob - Added on 2025-09-23 01:27:10.924127
!(add-atom &users (user bob))
!(add-atom &users (watched bob m_tt0245165))


; User: bob - Added on 2025-09-23 01:27:18.557105
!(add-atom &users (user bob))
!(add-atom &users (watched bob m_tt21262240))


; User: bob - Added on 2025-09-23 01:27:20.158500
!(add-atom &users (user bob))
!(add-atom &users (watched bob m_tt9612516))


; User: bob - Added on 2025-09-23 02:19:10.129995
!(add-atom &users (user bob))
!(add-atom &users (liked bob m_tt0167260))


; User: prakhaar - Added on 2025-09-23 14:49:34.476050
!(add-atom &users (user prakhaar))
!(add-atom &users (fav-genre prakhaar "Action"))
!(add-atom &users (fav-genre prakhaar "Comedy"))
!(add-atom &users (fav-genre prakhaar "Drama"))
!(add-atom &users (fav-genre prakhaar "Fantasy"))
!(add-atom &users (fav-genre prakhaar "Thriller"))
!(add-atom &users (language prakhaar "English"))
!(add-atom &users (language prakhaar "Hindi"))
!(add-atom &users (country prakhaar "India"))
!(add-atom &users (liked prakhaar m_tt2911666))
!(add-atom &users (liked prakhaar m_tt0081573))
!(add-atom &users (liked prakhaar m_tt0463392))


; User: prakhaar - Added on 2025-09-23 14:54:12.421373
!(add-atom &users (user prakhaar))
!(add-atom &users (watched prakhaar m_tt0053546))


; User: prakhaar - Added on 2025-09-23 14:54:21.218563
!(add-atom &users (user prakhaar))
!(add-atom &users (liked prakhaar m_tt1465522))


; User: prakhaar - Added on 2025-09-23 14:54:23.508249
!(add-atom &users (user prakhaar))
!(add-atom &users (watched prakhaar m_tt0029583))


; User: prakhaar - Added on 2025-09-23 14:54:27.341642
!(add-atom &users (user prakhaar))
!(add-atom &users (liked prakhaar m_tt0245165))

